// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AppPruebaMVC.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AppPruebaMVC.Data.Context
{
    public partial class consultoriobdContext
    {
        private IconsultoriobdContextProcedures _procedures;

        public virtual IconsultoriobdContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new consultoriobdContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IconsultoriobdContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<sp_busqueda_personaResult>().HasNoKey().ToView(null);
        }
    }

    public partial class consultoriobdContextProcedures : IconsultoriobdContextProcedures
    {
        private readonly consultoriobdContext _context;

        public consultoriobdContextProcedures(consultoriobdContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_busqueda_personaResult>> sp_busqueda_personaAsync(string busqueda, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "busqueda",
                    Size = 20,
                    Value = busqueda ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_busqueda_personaResult>("EXEC @returnValue = [dbo].[sp_busqueda_persona] @busqueda", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
