// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AppPruebaMVC.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AppPruebaMVC.Data.Context
{
    public partial interface IconsultoriobdContextProcedures
    {
        Task<List<sp_busqueda_personaResult>> sp_busqueda_personaAsync(string busqueda, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
