// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Administrativo
    {
        public string Cargo { get; set; }
        public int Codigo { get; set; }

        public virtual Persona CodigoNavigation { get; set; }
    }
}