// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Admicion
    {
        public double FrecuenciaCardiaca { get; set; }
        public double FrecuenciaRespiratoria { get; set; }
        public string Ocupacion { get; set; }
        public double Peso { get; set; }
        public double PresionArterial { get; set; }
        public double Saturacion { get; set; }
        public double Temperatura { get; set; }
        public int Codigo { get; set; }
        public int CodCita { get; set; }
        public int CodEnfermera { get; set; }
        public DateTime? FechaAdmicion { get; set; }

        public virtual CitaMedica CodCitaNavigation { get; set; }
        public virtual Enfermera CodEnfermeraNavigation { get; set; }
    }
}