// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Citum
    {
        public Citum()
        {
            RecetaMedicas = new HashSet<RecetaMedica>();
            Resultados = new HashSet<Resultado>();
            Triajes = new HashSet<Triaje>();
        }

        public bool Estado { get; set; }
        public DateTime Fecha { get; set; }
        public TimeSpan Hora { get; set; }
        public string Usuario { get; set; }
        public string Codigo { get; set; }
        public string Paciente { get; set; }

        public virtual Persona PacienteNavigation { get; set; }
        public virtual Usuario UsuarioNavigation { get; set; }
        public virtual ICollection<RecetaMedica> RecetaMedicas { get; set; }
        public virtual ICollection<Resultado> Resultados { get; set; }
        public virtual ICollection<Triaje> Triajes { get; set; }
    }
}