// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class DetalleDiagnostico
    {
        public string Tipo { get; set; }
        public string Codigo { get; set; }
        public string Resultado { get; set; }
        public string Diagnostico { get; set; }

        public virtual Diagnostico DiagnosticoNavigation { get; set; }
        public virtual Resultado ResultadoNavigation { get; set; }
    }
}