// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Diagnostico
    {
        public Diagnostico()
        {
            DetalleDiagnosticos = new HashSet<DetalleDiagnostico>();
        }

        public string Enfermedad { get; set; }
        public string Codigo { get; set; }

        public virtual ICollection<DetalleDiagnostico> DetalleDiagnosticos { get; set; }
    }
}