// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Enfermedad
    {
        public Enfermedad()
        {
            Diagnosticos = new HashSet<Diagnostico>();
        }

        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Codigo { get; set; }
        public bool Estado { get; set; }

        public virtual ICollection<Diagnostico> Diagnosticos { get; set; }
    }
}