// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Medicamento
    {
        public Medicamento()
        {
            RecetaMedicas = new HashSet<RecetaMedica>();
        }

        public string NombreMedicamento { get; set; }
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }

        public virtual ICollection<RecetaMedica> RecetaMedicas { get; set; }
    }
}