// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Paciente
    {
        public Paciente()
        {
            Admicions = new HashSet<Admicion>();
        }

        public string Alergia { get; set; }
        public string PersonaEncargada { get; set; }
        public int Codigo { get; set; }

        public virtual Persona CodigoNavigation { get; set; }
        public virtual ICollection<Admicion> Admicions { get; set; }
    }
}