// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Persona
    {
        public Persona()
        {
            Cita = new HashSet<Citum>();
        }

        public string Alergia { get; set; }
        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string NumeroCelular { get; set; }
        public string NumeroCedula { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string Nombre { get; set; }
        public string NumeroTelefono { get; set; }
        public string PersonaResponsable { get; set; }
        public bool Sexo { get; set; }
        public string Codigo { get; set; }

        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Citum> Cita { get; set; }
    }
}