// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Persona
    {
        public Persona()
        {
            Usuarios = new HashSet<Usuario>();
        }

        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string NumeroCelular { get; set; }
        public string Cedula { get; set; }
        public string Direccion { get; set; }
        public bool Estado { get; set; }
        public string EstadoCivil { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public bool Sexo { get; set; }
        public string NumeroTelefono { get; set; }
        public int Codigo { get; set; }
        public string Nombre { get; set; }

        public virtual Administrativo Administrativo { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Enfermera Enfermera { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}