// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class RecetaMedica
    {
        public string Cantidad { get; set; }
        public string Dosis { get; set; }
        public string Duracion { get; set; }
        public string Medicamento { get; set; }
        public string Codigo { get; set; }
        public string CodigoCita { get; set; }

        public virtual Citum CodigoCitaNavigation { get; set; }
    }
}