// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class RecetaMedica
    {
        public RecetaMedica()
        {
            Resultados = new HashSet<Resultado>();
        }

        public int Cantidad { get; set; }
        public double Dosis { get; set; }
        public int Duracion { get; set; }
        public int CodMedicamento { get; set; }
        public int Codigo { get; set; }

        public virtual Medicamento CodMedicamentoNavigation { get; set; }
        public virtual ICollection<Resultado> Resultados { get; set; }
    }
}