// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Resultado
    {
        public Resultado()
        {
            DetalleDiagnosticos = new HashSet<DetalleDiagnostico>();
        }

        public string Antecedentes { get; set; }
        public bool Estado { get; set; }
        public DateTime Fecha { get; set; }
        public string Motivo { get; set; }
        public DateTime ProximaCita { get; set; }
        public string TiempoEnfermedad { get; set; }
        public string Tratamiento { get; set; }
        public string Codigo { get; set; }
        public string CodigoCita { get; set; }

        public virtual Citum CodigoCitaNavigation { get; set; }
        public virtual ICollection<DetalleDiagnostico> DetalleDiagnosticos { get; set; }
    }
}