// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Resultado
    {
        public Resultado()
        {
            Diagnosticos = new HashSet<Diagnostico>();
        }

        public string Antecedentes { get; set; }
        public bool Estado { get; set; }
        public DateTime FechaResultado { get; set; }
        public string MotivoConsulta { get; set; }
        public DateTime ProximaCita { get; set; }
        public string TiempoEnfermedad { get; set; }
        public int Codigo { get; set; }
        public int CodCita { get; set; }
        public int? Codtratamiento { get; set; }

        public virtual CitaMedica CodCitaNavigation { get; set; }
        public virtual RecetaMedica CodtratamientoNavigation { get; set; }
        public virtual ICollection<Diagnostico> Diagnosticos { get; set; }
    }
}