// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Role
    {
        public Role()
        {
            RolUsuarios = new HashSet<RolUsuario>();
        }

        public string Rol { get; set; }
        public int Codigo { get; set; }

        public virtual ICollection<RolUsuario> RolUsuarios { get; set; }
    }
}