// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class RolUsuario
    {
        public RolUsuario()
        {
            RolUsuario1s = new HashSet<RolUsuario1>();
        }

        public string Rol { get; set; }
        public int Codigo { get; set; }

        public virtual ICollection<RolUsuario1> RolUsuario1s { get; set; }
    }
}