// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class RolUsuario1
    {
        public int Codigo { get; set; }
        public int Faurcodrou { get; set; }
        public int Faurcodusu { get; set; }

        public virtual RolUsuario FaurcodrouNavigation { get; set; }
        public virtual Usuario FaurcodusuNavigation { get; set; }
    }
}