// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class RolUsuario
    {
        public int Codigo { get; set; }
        public int CodRol { get; set; }
        public int CodUsuario { get; set; }

        public virtual Role CodRolNavigation { get; set; }
        public virtual Usuario CodUsuarioNavigation { get; set; }
    }
}