// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppPruebaMVC.Data.Models
{
    public partial class sp_busqueda_personaResult
    {
        public int papscodper { get; set; }
        public string persona { get; set; }
        public string capscedul { get; set; }
        public string capsnomper { get; set; }
        public string capsapepat { get; set; }
        public string capsapemat { get; set; }
    }
}
