// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Tratamiento
    {
        public int Codigo { get; set; }
        public int CodCita { get; set; }
        public int CodRecetaMedica { get; set; }

        public virtual CitaMedica CodCitaNavigation { get; set; }
        public virtual RecetaMedica CodRecetaMedicaNavigation { get; set; }
    }
}