// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Triaje
    {
        public string FrecuenciaCardiaca { get; set; }
        public string FrecuenciaRespiratoria { get; set; }
        public string Ocupacion { get; set; }
        public float Peso { get; set; }
        public string PresionArterial { get; set; }
        public string Saturacion { get; set; }
        public string Temperatura { get; set; }
        public string Codigo { get; set; }
        public string CodigoCita { get; set; }

        public virtual Citum CodigoCitaNavigation { get; set; }
    }
}