// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Cita = new HashSet<Citum>();
        }

        public string Cargo { get; set; }
        public string Contrasena { get; set; }
        public string Correo { get; set; }
        public string Especialidad { get; set; }
        public string TipoUsuario { get; set; }
        public string Codigo { get; set; }

        public virtual Persona CodigoNavigation { get; set; }
        public virtual TipoUsuario TipoUsuarioNavigation { get; set; }
        public virtual ICollection<Citum> Cita { get; set; }
    }
}