// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppPruebaMVC.Data.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            CitaMedicas = new HashSet<CitaMedica>();
            RolUsuario1s = new HashSet<RolUsuario1>();
        }

        public string Contrasena { get; set; }
        public string Correo { get; set; }
        public string Usuario1 { get; set; }
        public int Codigo { get; set; }
        public int CodPersona { get; set; }

        public virtual Persona CodPersonaNavigation { get; set; }
        public virtual ICollection<CitaMedica> CitaMedicas { get; set; }
        public virtual ICollection<RolUsuario1> RolUsuario1s { get; set; }
    }
}